language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - sudo apt-get install sloccount
script:
  - sloccount ML-visualizer
  - chmod u+r+x run_tests_travis.bat
  - python run.py &
  - ./run_tests_travis.bat
