language: python
python:
  - "3.6" # current default Python on Travis CI
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
addons:
  hosts:
    - travis.dev
    - joshkalderimis.com
script:
  - chmod u+r+x run_tests.bat
  - python run.py
  - ./run_tests.bat
