language: python
python:
  - "3.6" # current default Python on Travis CI
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
addons:
  hosts:
    - travis.dev
    - joshkalderimis.com
script:
  - chmod u+r+x run_tests.bat
  - curl -d '{'email':'asd@asd.pl', 'username':'asd', 'password':'asd'}' -H "Content-Type: application/json" -X POST http://127.0.0.1:5050/signup
  - python run.py &
  - ./run_tests.bat
