name: Flake8-black Linter

on: [push, pull_request]

jobs:
  linter:
    name: Flake8-black Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8-black
      - name: Lint with flake8-black
        run: |
          flake8 ml_visualizer test MLV
