name: Unit Tests

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Pytest
        run: python -m unittest discover

  linter:
    name: Indentation  Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pylint
          # pip install -r requirements.txt
      - name: Lint with pylint
        run: |
          python -m pylint --disable=all -e W0311 --jobs=0 --indent-string='    ' **/*.py
